# Generated by Django 2.1.2 on 2018-12-18 08:09

import admin_wedbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produk', models.CharField(max_length=200)),
                ('post_thumbnail', models.ImageField(default='default.jpg', upload_to=admin_wedbook.models.path_and_rename)),
                ('kategori', models.CharField(choices=[('backdrop', 'Back Drop'), ('bedroom', 'Bedroom'), ('meja_meeting', 'Meja Meeting'), ('front_office', 'Front Office'), ('rak', 'Rak'), ('tangga', 'Tangga')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KomentarSaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pesan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_profil', models.CharField(default='profilnya', max_length=100)),
                ('foto_perusahaan', models.ImageField(default='default.jpg', upload_to=admin_wedbook.models.path_and_rename)),
                ('deskripsi_perusahaan', models.TextField()),
                ('foto1', models.ImageField(default='default.jpg', upload_to=admin_wedbook.models.path_and_rename)),
                ('nama_produk', models.CharField(max_length=100)),
                ('deskripsi_produk', models.TextField()),
                ('foto2', models.ImageField(default='default.jpg', upload_to=admin_wedbook.models.path_and_rename)),
                ('nama_produk2', models.CharField(max_length=100)),
                ('deskripsi_produk2', models.TextField()),
                ('foto3', models.ImageField(default='default.jpg', upload_to=admin_wedbook.models.path_and_rename)),
                ('nama_produk3', models.CharField(max_length=100)),
                ('deskripsi_produk3', models.TextField()),
                ('nama_dan_pekerjaan', models.CharField(max_length=100)),
                ('project_dan_asal', models.CharField(max_length=100)),
                ('komentar', models.TextField()),
                ('nama_dan_pekerjaan2', models.CharField(max_length=100)),
                ('project_dan_asal2', models.CharField(max_length=100)),
                ('komentar2', models.TextField()),
                ('nama_dan_pekerjaan3', models.CharField(max_length=100)),
                ('project_dan_asal3', models.CharField(max_length=100)),
                ('komentar3', models.TextField()),
                ('alamat', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('google_plus', models.URLField()),
            ],
        ),
    ]
