# Generated by Django 2.1.2 on 2018-12-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_wedbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='deskripsi_produk',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='deskripsi_produk2',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='deskripsi_produk3',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='foto1',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='foto3',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='komentar',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='komentar2',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='komentar3',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nama_dan_pekerjaan',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nama_dan_pekerjaan2',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nama_dan_pekerjaan3',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nama_produk',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nama_produk2',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nama_produk3',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='project_dan_asal',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='project_dan_asal2',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='project_dan_asal3',
        ),
    ]
