# Generated by Django 2.1.2 on 2018-12-18 04:17

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='sub_tittle',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_thumbnail',
            field=models.ImageField(default='blog.jpg', upload_to=blog.models.path_and_rename),
        ),
    ]
